#!/usr/bin/env python3
"""
Alias Generator for Task-Agents MCP Server

Generates executable shell scripts that allow direct invocation of agents from terminal.
Each agent gets its own executable script that mimics the MCP server's command building.
"""

import os
import stat
import shutil
import logging
import sys
from pathlib import Path
from typing import Dict, List, Optional

# Import AgentManager from the main package - add to path dynamically
def _import_agent_manager():
    """Import AgentManager from the main package."""
    try:
        # Try to import from the main package if already available
        from task_agents_mcp.agent_manager import AgentManager, AgentConfig
        return AgentManager, AgentConfig
    except ImportError:
        # Add the src directory to path and try again
        current_dir = Path(__file__).parent.parent.parent
        src_dir = current_dir / "src"
        if src_dir.exists():
            sys.path.insert(0, str(src_dir))
            from task_agents_mcp.agent_manager import AgentManager, AgentConfig
            return AgentManager, AgentConfig
        else:
            raise ImportError("Could not locate task_agents_mcp.agent_manager module")

logger = logging.getLogger(__name__)


class AliasGenerator:
    """Generates executable alias scripts for each agent."""
    
    def __init__(self, agent_manager):
        """Initialize with an AgentManager instance."""
        self.agent_manager = agent_manager
        # Import the types we need
        self.AgentManager, self.AgentConfig = _import_agent_manager()
    
    def generate_alias_script(self, agent_config, output_dir: Path) -> str:
        """Generate a shell script for a specific agent."""
        
        # Sanitize agent name for filename (replace spaces and special chars with dashes)
        script_name = agent_config.agent_name.lower().replace(' ', '-').replace('_', '-')
        script_path = output_dir / script_name
        
        # Find Claude CLI path
        claude_path = self._find_claude_path()
        if not claude_path:
            raise RuntimeError("Claude CLI not found. Please install Claude Code CLI.")
        
        # Prepare the system prompt with proper shell escaping
        # Replace problematic characters that could be interpreted as commands
        escaped_system_prompt = (agent_config.system_prompt
                                .replace('\\', '\\\\')  # Escape backslashes first
                                .replace('"', '\\"')    # Escape quotes
                                .replace('`', '\\`')    # Escape backticks
                                .replace('$', '\\$')    # Escape dollar signs
                                )
        
        # Get the agent file path for dynamic loading
        agent_file_path = None
        for file_path in Path(self.agent_manager.configs_dir).glob("*.md"):
            try:
                with open(file_path, 'r', encoding='utf-8') as f:
                    content = f.read()
                    if '---\n' in content:
                        parts = content.split('---\n', 2)
                        if len(parts) >= 2:
                            import yaml
                            metadata = yaml.safe_load(parts[1])
                            if metadata and metadata.get('agent-name') == agent_config.agent_name:
                                agent_file_path = str(file_path)
                                break
            except Exception:
                continue
        
        if not agent_file_path:
            agent_file_path = f"{self.agent_manager.configs_dir}/{script_name}.md"
        
        # Build the shell script content with dynamic config loading
        script_content = '''#!/bin/bash
# Auto-generated alias script for agent: {agent_name}
# Generated by task-agent generate-aliases
# Note: This script dynamically loads agent config on each run

# Static configuration
CONFIG_DIR="{configs_dir}"
AGENT_FILE="{agent_file_path}"
CLAUDE_CLI="{claude_path}"

# Check if query was provided
if [ $# -eq 0 ]; then
    echo "Usage: {script_name} \\"your query here\\""
    echo ""
    echo "This is a dynamic agent alias that loads configuration from:"
    echo "$AGENT_FILE"
    exit 1
fi

# Get the query from command line arguments
QUERY="$*"

# Find Claude CLI
if [ ! -f "$CLAUDE_CLI" ]; then
    echo "Error: Claude CLI not found at $CLAUDE_CLI"
    echo "Please install Claude Code CLI or update the path in this script."
    exit 1
fi

# Check if agent file exists
if [ ! -f "$AGENT_FILE" ]; then
    echo "Error: Agent configuration file not found: $AGENT_FILE"
    exit 1
fi

# Parse agent configuration from MD file using Python
TEMP_CONFIG=$(mktemp)
python3 -c '
import sys
import yaml
import os

# Get file paths from command line arguments
if len(sys.argv) != 3:
    print("Usage: python3 script.py <agent_file> <temp_config>", file=sys.stderr)
    sys.exit(1)

agent_file = sys.argv[1]
temp_config = sys.argv[2]

# Read the agent file
try:
    with open(agent_file, "r", encoding="utf-8") as f:
        content = f.read()
    
    # Parse YAML frontmatter and system prompt
    if "---" not in content:
        print("Error: No YAML frontmatter found in agent file", file=sys.stderr)
        sys.exit(1)
    
    parts = content.split("---", 2)
    if len(parts) < 3:
        print("Error: Invalid YAML frontmatter format", file=sys.stderr)
        sys.exit(1)
    
    metadata = yaml.safe_load(parts[1])
    system_prompt_section = parts[2].strip()
    
    # Extract system prompt after System-prompt: marker
    system_prompt = ""
    if system_prompt_section.startswith("System-prompt:"):
        system_prompt = system_prompt_section[len("System-prompt:"):].strip()
    else:
        system_prompt = system_prompt_section
    
    # Get required fields
    agent_name = metadata.get("agent-name", "Unknown Agent")
    description = metadata.get("description", "No description")
    tools = metadata.get("tools", "Read,Write").replace(",", " ").split()
    model = metadata.get("model", "sonnet")
    cwd = metadata.get("cwd", ".")
    
    # Get optional fields
    optional = metadata.get("optional", {})
    resume_session = optional.get("resume-session", False)
    
    # Write config to temp file
    with open(temp_config, "w") as f:
        f.write("AGENT_NAME=\\"" + agent_name + "\\"\\n")
        f.write("AGENT_DESCRIPTION=\\"" + description + "\\"\\n")
        f.write("AGENT_MODEL=\\"" + model + "\\"\\n")
        f.write("AGENT_TOOLS=\\"" + " ".join(tools) + "\\"\\n")
        f.write("AGENT_CWD=\\"" + cwd + "\\"\\n")
        f.write("RESUME_SESSION=\\"" + str(resume_session).lower() + "\\"\\n")
    
    # Write system prompt to separate file
    with open(temp_config + ".prompt", "w") as f:
        f.write(system_prompt)
        
except Exception as e:
    print("Error parsing agent config: " + str(e), file=sys.stderr)
    sys.exit(1)
' "$AGENT_FILE" "$TEMP_CONFIG"

if [ $? -ne 0 ]; then
    echo "Error: Failed to parse agent configuration from $AGENT_FILE"
    echo "Please check the YAML frontmatter format."
    exit 1
fi

# Load the parsed configuration
source "$TEMP_CONFIG"

# Determine working directory
WORKING_DIR="$AGENT_CWD"
if [ "$WORKING_DIR" = "." ]; then
    # Resolve relative to parent of task-agents directory
    TASK_AGENTS_DIR=$(realpath "$CONFIG_DIR")
    WORKING_DIR=$(dirname "$TASK_AGENTS_DIR")
fi
WORKING_DIR=$(realpath "$WORKING_DIR")

echo "🚀 Starting $AGENT_NAME agent..."
echo "📂 Working directory: $WORKING_DIR"
echo "❓ Query: $QUERY"
echo ""

# Use the system prompt from the parsed config
TEMP_SYSTEM_PROMPT="$TEMP_CONFIG.prompt"

# Build Claude CLI command
CLAUDE_CMD=(
    "$CLAUDE_CLI"
    "-p" "$QUERY"
    "--output-format" "stream-json"
    "--verbose"
    "--allowedTools" $AGENT_TOOLS
    "--model" "$AGENT_MODEL"
    "--system-prompt-file" "$TEMP_SYSTEM_PROMPT"
    "--append-system-prompt" "WORKING DIRECTORY CONTEXT: You are currently operating from the directory: $WORKING_DIR"
)

# Add session resumption if enabled
if [ "$RESUME_SESSION" = "true" ]; then
    SESSION_STORE="/tmp/task_agents_sessions.json"
    
    # Check for --reset flag
    RESET_SESSION=false
    if [[ "$1" == "--reset" ]]; then
        RESET_SESSION=true
        shift
        QUERY="$*"
        echo "🔄 Session reset requested"
        
        # Update Claude command with new query
        CLAUDE_CMD[2]="$QUERY"
    fi
    
    # Handle session resumption
    if [ -f "$SESSION_STORE" ] && [ "$RESET_SESSION" = false ]; then
        # Try to get last session ID for this agent
        LAST_SESSION=$(grep -o "\\"$AGENT_NAME\\".*\\"session_id\\":\\"[^\\"]*\\"" "$SESSION_STORE" 2>/dev/null | tail -1 | sed -E 's/.*"session_id":"([^"]*)".*/\\1/')
        if [ -n "$LAST_SESSION" ]; then
            CLAUDE_CMD+=("-r" "$LAST_SESSION")
            echo "🔄 Resuming session: $LAST_SESSION"
        fi
    elif [ "$RESET_SESSION" = true ] && [ -f "$SESSION_STORE" ]; then
        # Clear session for this agent (if jq is available)
        if command -v jq >/dev/null 2>&1; then
            jq "del(.\\"$AGENT_NAME\\")" "$SESSION_STORE" > "${{SESSION_STORE}}.tmp" && mv "${{SESSION_STORE}}.tmp" "$SESSION_STORE"
            echo "🔄 Session cleared for $AGENT_NAME"
        fi
    fi
fi

'''
        
        # Resource directories and session resumption are now handled dynamically

        # Add the final execution part for all cases with MCP server-style JSON parsing
        script_content += '''
# Execute Claude CLI command and parse JSON stream like MCP server does
cd "$WORKING_DIR"

# Create temporary file for output
TEMP_OUTPUT=$(mktemp)

# Run Claude CLI and capture stream-json output
"${CLAUDE_CMD[@]}" > "$TEMP_OUTPUT" 2>&1
CLAUDE_EXIT_CODE=$?

# Parse the JSON stream like MCP server does
if [ $CLAUDE_EXIT_CODE -eq 0 ]; then
    # Initialize variables
    SESSION_ID=""
    ASSISTANT_MESSAGES=""
    TOOLS_USED=""
    TOKEN_USAGE=""
    FINAL_RESULT=""
    
    # Parse each JSON line
    while IFS= read -r line; do
        if [ -n "$line" ]; then
            # Extract session ID from system init event
            if echo "$line" | grep -q '"type":"system"' && echo "$line" | grep -q '"subtype":"init"'; then
                SESSION_ID=$(echo "$line" | grep -o '"session_id":"[^"]*"' | cut -d'"' -f4)
            fi
            
            # Extract assistant text messages
            if echo "$line" | grep -q '"type":"assistant"'; then
                # Look for text content in assistant messages
                if echo "$line" | grep -q '"type":"text"'; then
                    TEXT_CONTENT=$(echo "$line" | sed -n 's/.*"text":"\\([^"]*\\)".*/\\1/p' | head -1)
                    if [ -n "$TEXT_CONTENT" ]; then
                        ASSISTANT_MESSAGES="${ASSISTANT_MESSAGES}${TEXT_CONTENT}\\n"
                    fi
                fi
                
                # Track tool usage
                if echo "$line" | grep -q '"type":"tool_use"'; then
                    TOOL_NAME=$(echo "$line" | grep -o '"name":"[^"]*"' | cut -d'"' -f4)
                    if [ -n "$TOOL_NAME" ]; then
                        if [ -z "$TOOLS_USED" ]; then
                            TOOLS_USED="$TOOL_NAME"
                        else
                            TOOLS_USED="$TOOLS_USED, $TOOL_NAME"
                        fi
                    fi
                fi
            fi
            
            # Extract final result from result event (takes precedence over assistant messages)
            if echo "$line" | grep -q '"type":"result"'; then
                RESULT_TEXT=$(echo "$line" | sed -n 's/.*"result":"\\([^"]*\\)".*/\\1/p')
                if [ -n "$RESULT_TEXT" ]; then
                    FINAL_RESULT="$RESULT_TEXT"
                fi
                
                # Extract token usage
                INPUT_TOKENS=$(echo "$line" | grep -o '"input_tokens":[0-9]*' | cut -d':' -f2)
                OUTPUT_TOKENS=$(echo "$line" | grep -o '"output_tokens":[0-9]*' | cut -d':' -f2)
                if [ -n "$INPUT_TOKENS" ] && [ -n "$OUTPUT_TOKENS" ]; then
                    TOTAL_TOKENS=$((INPUT_TOKENS + OUTPUT_TOKENS))
                    TOKEN_USAGE="Tokens: $TOTAL_TOKENS ($INPUT_TOKENS in, $OUTPUT_TOKENS out)"
                fi
            fi
        fi
    done < "$TEMP_OUTPUT"
    
    # Format output like MCP server
    if [ -n "$SESSION_ID" ]; then
        echo "Session: $SESSION_ID"
    fi
    
    if [ -n "$TOOLS_USED" ]; then
        echo "Tools used: $TOOLS_USED"
        echo ""
    fi
    
    # Use final result if available, otherwise use assistant messages
    if [ -n "$FINAL_RESULT" ]; then
        echo -e "$FINAL_RESULT"
    elif [ -n "$ASSISTANT_MESSAGES" ]; then
        echo -e "$ASSISTANT_MESSAGES"
    else
        echo "Task completed but no response was generated."
    fi
    
    if [ -n "$TOKEN_USAGE" ]; then
        echo ""
        echo "$TOKEN_USAGE"
    fi
else
    echo "Error executing Claude CLI (exit code: $CLAUDE_EXIT_CODE)"
    cat "$TEMP_OUTPUT" >&2
fi

# Cleanup temp files
rm -f "$TEMP_CONFIG" "$TEMP_CONFIG.prompt" "$TEMP_OUTPUT"
'''
        
        # Apply template substitution using string replacement to avoid format() issues
        script_content = script_content.replace('{agent_name}', str(agent_config.agent_name))
        script_content = script_content.replace('{configs_dir}', str(self.agent_manager.configs_dir))
        script_content = script_content.replace('{agent_file_path}', str(agent_file_path))
        script_content = script_content.replace('{claude_path}', str(claude_path))
        script_content = script_content.replace('{script_name}', str(script_name))

        return script_content, str(script_path)
    
    def _find_claude_path(self) -> Optional[str]:
        """Find the Claude CLI executable path."""
        # Check environment variable first
        claude_path = os.environ.get('CLAUDE_EXECUTABLE_PATH')
        if claude_path and os.path.exists(claude_path):
            return claude_path
        
        # Try to find in PATH
        claude_path = shutil.which('claude')
        if claude_path:
            return claude_path
        
        # Check common installation locations
        common_paths = [
            os.path.expanduser('~/.claude/local/claude'),
            '/usr/local/bin/claude',
            '/opt/homebrew/bin/claude'
        ]
        
        for path in common_paths:
            if os.path.exists(path) and os.access(path, os.X_OK):
                return path
        
        return None
    
    def generate_all_aliases(self, output_dir: Path) -> Dict[str, str]:
        """Generate alias scripts for all loaded agents.
        
        Returns:
            Dict mapping agent names to script paths
        """
        if not self.agent_manager.agents:
            raise ValueError("No agents loaded. Please ensure agents are configured in your agents directory.")
        
        # Create output directory if it doesn't exist
        output_dir.mkdir(parents=True, exist_ok=True)
        
        generated_scripts = {}
        
        for agent_name, agent_config in self.agent_manager.agents.items():
            try:
                script_content, script_path = self.generate_alias_script(agent_config, output_dir)
                
                # Write the script file
                with open(script_path, 'w') as f:
                    f.write(script_content)
                
                # Make the script executable
                os.chmod(script_path, stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)
                
                generated_scripts[agent_config.agent_name] = script_path
                logger.info(f"Generated alias script: {script_path}")
                
            except Exception as e:
                import traceback
                logger.error(f"Failed to generate alias for {agent_config.agent_name}: {e}")
                logger.error(f"Full traceback:\n{traceback.format_exc()}")
                continue
        
        return generated_scripts
    
    def generate_installer_script(self, output_dir: Path, scripts: Dict[str, str]) -> str:
        """Generate an installer script to add aliases to PATH."""
        installer_path = output_dir / "install-aliases.sh"
        
        # Pre-calculate the scripts list to avoid complex expressions in template
        scripts_list = ' '.join(f'"{Path(path).name}"' for path in scripts.values())
        
        installer_content = f'''#!/bin/bash
# Installer script for task-agent aliases
# Generated by task-agent generate-aliases

SCRIPT_DIR="{output_dir}"
TARGET_DIR="$HOME/.local/bin"

# Ensure the target directory exists and is in PATH
mkdir -p "$TARGET_DIR"

echo "Installing task-agent aliases..."

# Copy or symlink scripts
SCRIPTS=({scripts_list})

for SCRIPT in "${{{{SCRIPTS[@]}}}}"; do
    SOURCE="$SCRIPT_DIR/$SCRIPT"
    TARGET="$TARGET_DIR/$SCRIPT"
    
    if [ -f "$SOURCE" ]; then
        # Create symlink (preferred) or copy
        if command -v ln >/dev/null 2>&1; then
            ln -sf "$SOURCE" "$TARGET"
            echo "Linked: $SCRIPT"
        else
            cp "$SOURCE" "$TARGET"
            chmod +x "$TARGET"
            echo "Copied: $SCRIPT"
        fi
    fi
done

# Check if ~/.local/bin is in PATH
if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
    echo ""
    echo "⚠️  $HOME/.local/bin is not in your PATH."
    echo "Add the following line to your shell's profile (~/.bashrc, ~/.zshrc, etc.):"
    echo ""
    echo "    export PATH=\\"\\$HOME/.local/bin:\\$PATH\\""
    echo ""
    echo "Then restart your terminal or run: source ~/.bashrc (or ~/.zshrc)"
else
    echo ""
    echo "✅ Installation complete! Your aliases are ready to use."
fi

echo ""
echo "Available aliases:"'''
        
        # Add the available aliases
        for agent_name, path in scripts.items():
            installer_content += f'\necho "  {Path(path).name} - {agent_name}"'
        
        installer_content += '''

echo ""
echo "Usage examples:"'''
        
        # Add usage examples
        for path in list(scripts.values())[:3]:
            installer_content += f'\necho "  {Path(path).name} \\"analyze this code\\""'

        with open(installer_path, 'w') as f:
            f.write(installer_content)
        
        os.chmod(installer_path, stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)
        
        return str(installer_path)


def generate_aliases_command(output_dir: Optional[str] = None, agents_dir: Optional[str] = None):
    """CLI command to generate agent aliases."""
    
    # Determine agents directory
    if agents_dir:
        config_dir = agents_dir
    else:
        config_dir = os.environ.get('TASK_AGENTS_PATH')
        if not config_dir:
            config_dir = os.path.join(os.getcwd(), "task-agents")
    
    # Determine output directory - use proper task-agents-alias directory
    if output_dir:
        output_path = Path(output_dir)
    else:
        # Use a proper task-agents-alias directory in user's home
        output_path = Path.home() / "task-agents-alias"
    
    try:
        # Initialize agent manager and load agents
        AgentManager, AgentConfig = _import_agent_manager()
        agent_manager = AgentManager(config_dir)
        agent_manager.load_agents()
        
        if not agent_manager.agents:
            print(f"❌ No agents found in {config_dir}")
            print("Please ensure you have agent configuration files (.md) in your agents directory.")
            return False
        
        # Generate aliases
        generator = AliasGenerator(agent_manager)
        scripts = generator.generate_all_aliases(output_path)
        
        if not scripts:
            print("❌ No alias scripts were generated.")
            return False
        
        # Generate installer script
        installer_path = generator.generate_installer_script(output_path, scripts)
        
        print(f"✅ Generated {len(scripts)} alias scripts in {output_path}")
        print("")
        print("Generated aliases:")
        for agent_name, script_path in scripts.items():
            script_name = Path(script_path).name
            print(f"  {script_name} - {agent_name}")
        
        print("")
        print("🚀 Auto-installing aliases...")
        
        # Auto-install the aliases
        try:
            import subprocess
            result = subprocess.run(['bash', installer_path], capture_output=True, text=True)
            
            if result.returncode == 0:
                print("✅ Aliases successfully installed!")
                print("")
                print("You can now use your agents directly from the terminal:")
                for agent_name, script_path in scripts.items():
                    script_name = Path(script_path).name
                    print(f"  {script_name} \"your query here\"")
                
                print("")
                print("Example:")
                first_script = Path(list(scripts.values())[0]).name
                print(f"  {first_script} \"explain how this agent system works\"")
            else:
                print("⚠️  Installation encountered issues. You can run manually:")
                print(f"   bash {installer_path}")
                if result.stderr:
                    print(f"Error: {result.stderr}")
        
        except Exception as e:
            print("⚠️  Auto-installation failed. You can run manually:")
            print(f"   bash {installer_path}")
            print(f"Error: {e}")
        
        return True
        
    except Exception as e:
        print(f"❌ Error generating aliases: {e}")
        return False


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Generate executable aliases for task-agent agents")
    parser.add_argument("--output-dir", help="Directory to output alias scripts (default: ~/.local/bin)")
    parser.add_argument("--agents-dir", help="Directory containing agent configurations (default: ./task-agents or TASK_AGENTS_PATH)")
    
    args = parser.parse_args()
    
    success = generate_aliases_command(args.output_dir, args.agents_dir)
    exit(0 if success else 1)