name: Publish to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.3)'
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Update version (if manual trigger)
      if: github.event_name == 'workflow_dispatch'
      run: |
        sed -i 's/version = "[0-9.]*"/version = "${{ github.event.inputs.version }}"/' pyproject.toml
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python -m twine upload dist/*
    
    - name: Verify installation
      run: |
        sleep 30  # Wait for PyPI to update
        pip install task-agents-mcp==${{ github.event.inputs.version || github.ref_name }}
        python -c "import task_agents_mcp; print('Successfully installed!')"